### ISSUE TITLE
Clarify POST-redirect-GET status code

### ISSUE THREAD

**Issue by lefloh** [mvc-spec/mvc-spec#100]
Currently the [spec states about the PRG pattern][1]:

>In either case, the HTTP status code returned is 302 and relative paths are resolved 
relative to the application path

I'd think that `303 See other` is the correct status code. This is also what Ozark is currently returning when you use `redirect:/foo`. 

But there's also a test example [where explicitly `302 Found` is used][2] so I'm unsure if this was intended.

 [1]: https://github.com/mvc-spec/mvc-spec/blob/master/spec/chapters/controllers.tex#L178
 [2]: https://github.com/mvc-spec/ozark/blob/master/test/redirect/src/main/java/org/mvcspec/ozark/test/redirect/RedirectController.java#L58

**Comment by lefloh** [comment]
The HTTP specification explicitly describes the [302](https://tools.ietf.org/html/rfc7231#section-6.4.3) redirect as temporary where _"the client ought to continue to use the effective request URI for future requests"_. This is exactly what you want to avoid with a PRG.
The description of the [303](https://tools.ietf.org/html/rfc7231#section-6.4.4) redirect includes: _"It is primarily used to allow the output of a POST action to redirect the user agent to a selected resource, since doing so provides the information corresponding to the POST response in a form that can be separately identified, bookmarked, and cached, independent of the original request."_

I'll provide a PR to change the 302 to a 303.

**Comment by chkal** [comment]
I would like to share my thoughts on this one.

The fact that the spec document and the RI are using different status codes is of course a bug that must be fixed. No doubt about that.

In practice both 302 and 303 seem to be handled the same way by modern browsers. However, from the HTTP specification side there are some differences:

* 302 Found
  * Available since HTTP 1.0
  * Doesn't specify at all if the client MUST or MUST NOT use the same or different HTTP method for the following request
  * All modern browsers seem to use a GET even if the original request was a POST
* 303 See Other
  * Available since HTTP 1.1
  * Is basically the same as 302 but also enforces that the new request is using the GET method
  * Seems to be intended for the PRG use case

So we have to consider a few things:

* HTTP 1.0 clients may not support the 303 status code
* However, the HTTP 1.1 spec has been released in 1999, so it may be OK to use 303 today
* The 302 status code doesn't enforce the behavior we want, although all brothers seems to do it that way
* The Servlet API uses the 302 status code for `HttpServletResponse#sendRedirect`
* Most other frameworks also [use 302 for redirects](https://stackoverflow.com/a/5129154/395181). But maybe for historic reasons.

So 303 is definitely the correct one but requires HTTP 1.1 and 302 will most likely work everywhere but is badly specified.

To be honest, I don't know which one we should use. But what about leaving some room for implementations in the spec? We could for example write:

> In either case, the HTTP status code returned **is 303 or 302** [...]

Or perhaps modify the whole paragraph a bit and include:

> Implementations **SHOULD use a 303 status code** for the redirect but **MAY prefer 302** if HTTP 1.0 compatibility is required.

What do you think?

**Comment by lefloh** [comment]
I like your second proposal. I wouldn't force `302` as default as HTTP 1.1 is 19 years old by now.

JAX-RS also [suggests to use a 303 for PRG](https://javaee.github.io/javaee-spec/javadocs/javax/ws/rs/core/Response.html#seeOther-java.net.URI-):

>public static Response.ResponseBuilder seeOther(URI location)
>
>Create a new ResponseBuilder for a redirection. Used in the redirect-after-POST (aka POST/redirect/GET) pattern.
