### ISSUE TITLE
Show definition of BeforeControllerEvent et al. in spec

### ISSUE THREAD

**Issue by gunnarmorling** [mvc-spec/mvc-spec#112]
Hey, the source code of the even types listed in chapter 5 should be part of the spec (applies all API types really, the events caught my attention, though).

**Comment by phillip-kruger** [comment]
Hi Gunnar.
@chkal @ivargrimstad should I add it ?
We can also link to it maybe ?
[BeforeControllerEvent.java](https://github.com/mvc-spec/mvc-spec/blob/master/api/src/main/java/javax/mvc/event/BeforeControllerEvent.java)

Let me know

**Comment by gunnarmorling** [comment]
For Bean Validation we made very good experiences with including the actual source files from the API into the spec document, e.g. here: https://github.com/beanvalidation/beanvalidation-spec/blame/master/sources/constraint-definition.asciidoc#L25. For that, we copy the API sources into some staging dir in the spec repo, from where AsciiDoc then can resolve the includes.

Overall it's much better then manually copying the API types into the spec document, which will easily get out of date when doing that. There's still some adjustments to be done to the line numbers given at the include every now and then, but that's managable. AsciiDoc also allows to use comments instead to mark sections within the included source file, but we decided against that so to not pollute the actual API sources with those markers.

**Comment by ivargrimstad** [comment]
Including the source is pretty easy for us since we have the API sources and spec asciidoc files in the same repo, so we can probably get away without any extra copying...

**Comment by gunnarmorling** [comment]
Oh yeah, then it's even easier. And as long as you include entire files, you won't have trouble due to changing line numbers, too. It's only if you include just parts of it (say, to include a single nested type), then the offsets given for the include may require to be updated after updating that source file. But as said it's not a big deal in practice, we just did a final review pass at the end to make sure everything is alright.

**Comment by phillip-kruger** [comment]
Hi All
I had a quick look at this. It's easy enough to include the source file in the spec, as an example I included the `BeforeControllerEvent.java` in the events chapter (events.asciidoc)

In this example the part that we are interested in is just 3 lines, however due to licence header and comments it uses 52 lines:

![image](https://user-images.githubusercontent.com/6836179/33570270-f77f76ca-d934-11e7-86f9-887d70cf15d1.png)

In my opinion, this will clutter the spec document.

We can remove the licence part by only starting at line 15, but that still leave us with 30+ lines for a 3 line source code.

We can maybe only include the java parts (so ignore all comments), but that will break easy as soon as the source changes:

```
include::{mvc-api-source-dir}javax/mvc/event/BeforeControllerEvent.java[lines=16..19]
include::{mvc-api-source-dir}javax/mvc/event/BeforeControllerEvent.java[lines=35..36]
include::{mvc-api-source-dir}javax/mvc/event/BeforeControllerEvent.java[lines=43..44]
include::{mvc-api-source-dir}javax/mvc/event/BeforeControllerEvent.java[lines=51..52]
```
![image](https://user-images.githubusercontent.com/6836179/33570797-b05d51ac-d936-11e7-8558-17dc7d18a55d.png)

Another option is to look for (or write) a maven plugin that copy the source and filter the comments out and include that. ?

Or write a custom include module for asciidoctor, that ignore comments ?

Or just link to the raw source in github (as per my initial comment)

Let me know what you guys think. 

1) Include the file as is, licence and comments included.
2) Include the file as is but only from after the licence.
3) Include only the source parts
4) Use maven to copy and filter out the comments
5) Write a custom asciidoctor include module that filter out the comments
6) Just add a link to the source in github

Maybe there are another solution I am missing ?

Let me know.

**Comment by gunnarmorling** [comment]
To give one data point, for BV we decided to include full sources including comments, but without the license header (doesn't make sense to repeat that over and over) and without import statements. 

We also omitted the package definition for types in the root package of the spec (where most types are located) and only added it for types in other packages. We found that to be a good compromise betweeen having all useful information within the spec document and avoiding too much bloat.

I'd definitely recommend to have all types in the document so to make it self-contained and better to consume for readers, and I'd also recommend to have comments in there, as they form part of the spec (e.g. whether allowed values for parameters, whether a method may return null etc.).

Btw. I'd recommend to omit the `@see` tags if they just point to the return type of the method. Rendered JavaDoc will have a link to that type anyways, so there's no value in adding it again via `@see`.

**Comment by chkal** [comment]
Hey all. Sorry for joining the discussion so late.

I basically agree that including the source of relevant Java classes and interfaces is good thing. And AsciiDoc even makes this super easy for us. So +1 for that.

I also agree that including the full file would be too verbose. Especially because of the license header. Therefore, I think should include everything except for the license header, the package declaration and the imports. So basically we would start with the javadocs on the type. IMO it is fine to drop package declaration and imports because class names are unique in MVC anyways and imports are usually too verbose. For this kind of detail people should simply look at the full javadocs or the API source. I think that basically matches how source code for examples is currently included in the spec.

What do you think?

**Comment by ivargrimstad** [comment]
I agree. Start with the JavaDoc sounds like the best solution

**Comment by phillip-kruger** [comment]
OK Cool. So in my example above it would then be:

`include::{mvc-api-source-dir}javax/mvc/event/BeforeControllerEvent.java[lines=21..-1]`
And that would create:
![image](https://user-images.githubusercontent.com/6836179/33703134-77a81464-db2f-11e7-9227-a59f355e1a2d.png)

Are we doing this on all MVC api classes referenced in the spec ?

Let me know, then I can start with the update.

**Comment by chkal** [comment]
Not sure if we really need to do it with ALL to be honest. I mean, do we really want to also include the source for annotations like `Controller` and `MvcBinding`. They don't contain much useful information for the reader.

**Comment by phillip-kruger** [comment]
In my example above the javadoc on the type is a repeat of what is already in the doc as the doc already contain an explanation and example code:
![screenshot_mvc1](https://user-images.githubusercontent.com/6836179/33704679-16c9e8b4-db36-11e7-907b-d6f8416212eb.png)
![screenshot_mvc2](https://user-images.githubusercontent.com/6836179/33704692-19e7ef50-db36-11e7-87a2-220c0807df5b.png)
 
Maybe we should start at the type (so after the type javadoc) ?

**Comment by chkal** [comment]
I don't think that a little bit of duplication is a real issue to be honest. In extreme cases we can also adjust the spec document. IMHO the spec contains some sections which read too much like a tutorial and not like a specification any way. But I guess we can adjust this later on.

**Comment by phillip-kruger** [comment]
OK I can start with the inclution of some source. Will do a PR soon.

**Comment by chkal** [comment]
I guess we can close this one, correct?

**Comment by chkal** [comment]
Looks like this can be closed. Feel free to comment on this issue if you think that we missed something.
